# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-19 05:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('desc', models.TextField()),
                ('owner', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=50)),
                ('group', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Rating_a',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(max_length=50)),
                ('value', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Rating_c',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(max_length=50)),
                ('value', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Rating_i',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(max_length=50)),
                ('value', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Types',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='activ',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activ.Location'),
        ),
        migrations.AddField(
            model_name='activ',
            name='rating_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activ.Rating_a'),
        ),
        migrations.AddField(
            model_name='activ',
            name='rating_c',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activ.Rating_c'),
        ),
        migrations.AddField(
            model_name='activ',
            name='rating_i',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activ.Rating_i'),
        ),
        migrations.AddField(
            model_name='activ',
            name='types',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activ.Types'),
        ),
    ]
