# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-25 16:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('activ', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activ',
            options={'ordering': ['-created'], 'verbose_name': 'Актив', 'verbose_name_plural': 'Активы'},
        ),
        migrations.AddField(
            model_name='activ',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 3, 25, 16, 20, 58, 313913, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activ',
            name='desc',
            field=models.TextField(verbose_name='Описание актива'),
        ),
        migrations.AlterField(
            model_name='activ',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activ.Location', verbose_name='Местоположение'),
        ),
        migrations.AlterField(
            model_name='activ',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Имя актива'),
        ),
        migrations.AlterField(
            model_name='activ',
            name='owner',
            field=models.CharField(max_length=200, verbose_name='Владелец актива'),
        ),
        migrations.AlterField(
            model_name='activ',
            name='rating_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activ.Rating_a', verbose_name='Доступность'),
        ),
        migrations.AlterField(
            model_name='activ',
            name='rating_c',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activ.Rating_c', verbose_name='Конфиденциальность'),
        ),
        migrations.AlterField(
            model_name='activ',
            name='rating_i',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activ.Rating_i', verbose_name='Целостность'),
        ),
        migrations.AlterField(
            model_name='activ',
            name='types',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activ.Types', verbose_name='Тип актива'),
        ),
        migrations.AlterField(
            model_name='location',
            name='group',
            field=models.CharField(max_length=100, verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='location',
            name='location',
            field=models.CharField(max_length=50, verbose_name='Местоположение'),
        ),
        migrations.AlterField(
            model_name='rating_a',
            name='rating',
            field=models.CharField(max_length=50, verbose_name='Оценка доступности'),
        ),
        migrations.AlterField(
            model_name='rating_a',
            name='value',
            field=models.IntegerField(default=0, verbose_name='Значение'),
        ),
        migrations.AlterField(
            model_name='rating_c',
            name='rating',
            field=models.CharField(max_length=50, verbose_name='Оценка конфиденциальности'),
        ),
        migrations.AlterField(
            model_name='rating_c',
            name='value',
            field=models.IntegerField(default=0, verbose_name='Значение'),
        ),
        migrations.AlterField(
            model_name='rating_i',
            name='rating',
            field=models.CharField(max_length=50, verbose_name='Оценка целостности'),
        ),
        migrations.AlterField(
            model_name='rating_i',
            name='value',
            field=models.IntegerField(default=0, verbose_name='Значение'),
        ),
        migrations.AlterField(
            model_name='types',
            name='types',
            field=models.CharField(max_length=250, verbose_name='Типы активов'),
        ),
    ]
