# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-21 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activ', '0003_auto_20160419_1431'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rating_a',
            options={'ordering': ('value',), 'verbose_name': 'Доступность', 'verbose_name_plural': 'Доступность'},
        ),
        migrations.AlterModelOptions(
            name='rating_c',
            options={'ordering': ('value',), 'verbose_name': 'Конфиденциальность', 'verbose_name_plural': 'Конфиденциальность'},
        ),
        migrations.AlterModelOptions(
            name='rating_i',
            options={'ordering': ('value',), 'verbose_name': 'Целостность', 'verbose_name_plural': 'Целостность'},
        ),
        migrations.AlterModelOptions(
            name='types',
            options={'ordering': ('types',), 'verbose_name': 'Тип актива', 'verbose_name_plural': 'Типы активов'},
        ),
        migrations.AlterField(
            model_name='types',
            name='types',
            field=models.IntegerField(choices=[(0, 'Бумажный документ'), (1, 'Электронный документ'), (2, 'Физический сервер'), (3, 'Виртуальный сервер'), (4, 'Канал связи'), (5, 'Мобильное устройство'), (6, 'Ноутбук'), (7, 'Оборудование'), (8, 'Персонал'), (9, 'Помещение'), (10, 'Печатающее устройство'), (11, 'Программный'), (12, 'Сервис'), (13, 'Сетевое оборудование'), (14, 'Сканер'), (15, 'Стационарный компьютер'), (16, 'Факс'), (17, 'Электронынй носитель'), (18, 'IP телефония')], verbose_name='Типы активов'),
        ),
    ]
