# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-15 06:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activ', '0004_auto_20160421_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activ',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='activ',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Актив'),
        ),
        migrations.AlterField(
            model_name='types',
            name='types',
            field=models.IntegerField(choices=[(0, 'Бумажный документ'), (1, 'Электронный документ'), (2, 'Физический сервер'), (3, 'Виртуальный сервер'), (4, 'Канал связи'), (5, 'Мобильное устройство'), (6, 'Ноутбук'), (7, 'Оборудование'), (8, 'Персонал'), (9, 'Помещение'), (10, 'Печатающее устройство'), (11, 'Программный'), (12, 'Сервис'), (13, 'Сетевое оборудование'), (14, 'Сканер'), (15, 'Стационарный компьютер'), (16, 'Телефония'), (17, 'Электронный носитель')], verbose_name='Типы активов'),
        ),
    ]
